services:
  kafka:
    image: confluentinc/cp-kafka:7.8.3
    container_name: kafka
    ports:
      - "9092:9092"
    healthcheck:
      test: [ "CMD-SHELL", "kafka-cluster cluster-id --bootstrap-server localhost:9092 || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s

    environment:
      KAFKA_KRAFT_MODE: 'true'

      CLUSTER_ID: '1L6g7nGhU-eAKfL--X25wo'
      KAFKA_NODE_ID: 1

      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs

    volumes:
      - kafka_kraft:/var/lib/kafka/data

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongovolume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: kodi
      MONGO_INITDB_ROOT_PASSWORD: word
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping').ok" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  redis:
    image: redis:latest
    #restart: always
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5

  kitchen_worker:
    build: /kitchen
    restart: always
    environment:
      HOST: mongo
      PORT: 27017
      USER: kodi
      PASSWORD: word
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PYTHONUNBUFFERED: 1
    depends_on:
      kafka:
        condition: service_healthy

  preprocessor:
    build: /preprocessor
    environment:
      HOST: mongo
      PORT: 27017
      USER: kodi
      PASSWORD: word
      PYTHONUNBUFFERED: 1
    depends_on:
      kafka:
        condition: service_healthy
  api:
    build: /api
    ports:
      - 8000:8000
    environment:
      HOST: mongo
      PORT: 27017
      USER: kodi
      PASSWORD: word
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      mongo:
        condition: service_healthy
      kafka:
        condition: service_healthy

  enricher:
    build: /enricher
    environment:
      HOST: mongo
      PORT: 27017
      USER: kodi
      PASSWORD: word
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PYTHONUNBUFFERED: 1
    depends_on:
      - preprocessor
      - mongo

volumes:
  kafka_kraft:
  mongovolume:
