apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: kobigdocker/api
        ports:
        - containerPort: 8000
        env:
        - name: HOST
          value: mongo
        - name: PORT
          value: "27017"
        - name: USER
          value: kodi
        - name: PASSWORD
          value: word
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
