apiVersion: apps/v1
kind: Deployment
metadata:
  name: enricher
  labels:
    app: enricher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enricher
  template:
    metadata:
      labels:
        app: enricher
    spec:
      containers:
      - name: enricher
        image: kobigdocker/enricher:v1.2
        env:
        - name: HOST
          value: mongo
        - name: PORT
          value: "27017"
        - name: USER
          value: kodi
        - name: PASSWORD
          value: word
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
        - name: PYTHONUNBUFFERED
          value: "1"
